### ISSUE TITLE
.transmit() wrongly documented

### ISSUE THREAD

**Issue by amstan** [tomstokes/python-spi#3]
According to your documentation one can just do `received = spi.transfer([0x11, 0x22, 0xFF])`. I would expect that to send a 3 bytes (17, 34, 255), but what it [actually does](https://github.com/tomstokes/python-spi/blob/master/spi.py#L425) is that it parses `[0x11, 0x22, 0xFF]` as `[17, 34, 255]` then it converts it to a string `"[17, 34, 255]"`, then it puts that in the buffer for sending, and since the length of the array is 3 (not 13 as the string is), it only sends `'[17'`(aka 91, 49, 55) down the spi pipe.

I really think that str() around data is wrong.

**Comment by tomstokes** [comment]
I originally had all of the functions work with binary strings, but converted them in a previous commit. Unfortunately I forgot to convert the transfer function when I did that.

Thanks for catching this and opening an issue so I could fix this. The new version should work as expected:

![screen shot 2015-09-10 at 1 08 24 pm](https://cloud.githubusercontent.com/assets/1216926/9798274/1cae1b5a-57bd-11e5-8bac-bea964d0e8fe.png)
