### ISSUE TITLE
io.UnsupportedOperation: File or stream is not seekable.

### ISSUE THREAD

**Issue by leaf-node** [tomstokes/python-spi#4]
I get this error when trying to open `/dev/spidev1.0` on a beaglebone black:

```
>>> x = spi.SPI("/dev/spidev1.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/spi.py", line 137, in __init__
    self.handle = open(device, "w+")
io.UnsupportedOperation: File or stream is not seekable.
```

**Comment by tomstokes** [comment]
What kernel and distribution are you using? I can't replicate this error on any of my BBBs here.

**Comment by tomstokes** [comment]
Let me know if you still can't get this to work and we can dive in to the problem. I'm going to close this issue until we have more details to work with or until someone can replicate the issue.

**Comment by leaf-node** [comment]
Sorry for not responding earlier. I believe the issue may have been a kernel issue on the BBB. I was only able to use `spidev1.0` with flashrom if i automatically loaded the `.dtbo` file at boot using the cape manager. if i tried loading it myself, then flashrom didn't detect the SPI chip. I imagine your script failed for similar reasons.

**Comment by tomstokes** [comment]
That was my first guess. I wish SPI on the BBB was easier to configure. Glad you got it figured out though.

**Comment by aule** [comment]
I have also had this issue, but it only occurs when running in python 3 and seems to be a lack of support for the 'w+' mode. This is on a Raspberry Pi 2 Model B v1.1.

```
pi@raspberrypi:~/card-reader $ python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> open("/dev/spidev0.0", "w+")
<open file '/dev/spidev0.0', mode 'w+' at 0x76c685a0>
```
```
pi@raspberrypi:~/card-reader $ python3
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> open("/dev/spidev0.0", "w+")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
io.UnsupportedOperation: File or stream is not seekable.
>>> open("/dev/spidev0.0", "w")
<_io.TextIOWrapper name='/dev/spidev0.0' mode='w' encoding='UTF-8'>
>>> open("/dev/spidev0.0", "r")
<_io.TextIOWrapper name='/dev/spidev0.0' mode='r' encoding='UTF-8'>
```

I've since managed to get the device (and MFRC522 card scanner) working with spidev instead, so it isn't necessarily the underlying hardware or drivers.
